### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by seisfeld** [dbuezas/arduino-web-uploader#1]
Hi David,

awesome project! Here are some suggestions:

- [ ] Make it possible to filter by VID and PID using optional parameters of the button object like:

```html
<button arduino-uploader hex-href="[path to your hex file]" board="[name of the board]" vid="[vendor id]" pid="[product id]" verify [optional]>
  Upload blinker to lgt8f328p and verify uploaded code
  <span class="upload-progress"></span>
</button>
```

- [ ] Change the warning when the experimental flag is not enabled from "get a token" to "enable the experimental flag" until the feature turns final in 2021.

- [ ] Rename the test.ts wrapper to something more meaningful, as using it that way (while maybe 2000s ;-)) is really cool and simple.

**Comment by dbuezas** [comment]
Good points, I'll add those next weekend :)
